vet:
ifndef MEGACHECK
	go get -u honnef.co/go/tools/cmd/megacheck
endif
	go vet ./...
	megacheck --ignore='github.com/kevinburke/vault-go/*.go:S1002' ./...

test:
	go test -short ./...

race-test: vet
	go test -race ./...
